## Multi-Layer Perceptron with Backpropagation
This exercise aims to show a multi-layer perceptron with a backpropagation function to update the parameters (weights and biases).

* [Import Dependencies](#id)
* [Defining Multi-Layer Perceptron](#dmlp)
* [Using the model](#utm)

### Importing Dependencies <a id = "id">

In [1]:
import numpy as np

### Defining Multi-Layer Perceptron <a id = "dmlp">

In [17]:
class MLP:
    def __init__(self, input_size, hidden_size, lr, epochs, output_size=1):
        self.lr = lr
        self.epochs = epochs
        self.hidden_size = hidden_size
        
        # Random initial parameters
        self.W1 = np.random.randn(input_size, hidden_size) * 0.01
        self.b1 = np.zeros((1, hidden_size))
        
        self.W2 = np.random.randn(hidden_size, output_size) * 0.01
        self.b2 = np.zeros((1, output_size))

In [18]:
# Activation Functions
def relu(self, z): return np.maximum(0, z)
def relu_deriv(self, z): return (z > 0).astype(float)

def sigmoid(self, z): return 1 / (1 + np.exp(-z))
def sigmoid_deriv(self, z): 
    s = self.sigmoid(z)
    return s * (1 - s)
  
MLP.relu = relu
MLP.relu_deriv = relu_deriv
MLP.sigmoid = sigmoid
MLP.sigmoid_deriv = sigmoid_deriv

In [19]:
# Forward Pass through parameters
def forward(self, X):
    # Hidden Layer (#1)
    self.z1 = np.dot(X, self.W1) + self.b1
    self.a1 = self.relu(self.z1)

    # Output Layer (#2)
    self.z2 = np.dot(self.a1, self.W2) + self.b2
    self.a2 = self.sigmoid(self.z2)
    return self.a2

MLP.forward = forward

In [20]:
def fit(self, X, y):
    y = y.reshape(-1, 1)

    for epoch in range(self.epochs):
        # Forward Pass
        prediction = self.forward(X)

        # Backpropagation (Output)
        error_out = prediction - y
        delta_out = error_out * self.sigmoid_deriv(self.z2)

        # Backpropagation (Hidden Layer)
        error_hidden = np.dot(delta_out, self.W2.T)
        delta_hidden = error_hidden * self.relu_deriv(self.z1)

        # Update Parameters
        self.W2 -= self.lr * np.dot(self.a1.T, delta_out)
        self.b2 -= self.lr * np.sum(delta_out, axis=0, keepdims=True)

        self.W1 -= self.lr * np.dot(X.T, delta_hidden)
        self.b1 -= self.lr * np.sum(delta_hidden, axis=0, keepdims=True)

        if epoch % 10000 == 0:
            loss = np.mean(np.square(error_out))
            print(f"W1: {self.W1},\nb1: {self.b1}, \nW2: {self.W2}, \nb2: {self.b2}")
            print(f"Epoch {epoch}, Loss: {loss:.6f}\n")
            
MLP.fit = fit

In [21]:
def predict(self, X):
    # Round the probability to 0 or 1
    return (self.forward(X) > 0.5).astype(int)

MLP.predict = predict

### Using the model <a id = "utm">

In [24]:
X_xor = np.array([[0,0], [0,1], [1,0], [1,1]])
y_xor = np.array([0, 1, 1, 0])

# Hidden size of at least 2 or 4 for XOR
model = MLP(input_size=2, hidden_size=4, lr=0.1, epochs = 10000)
model.fit(X_xor, y_xor)

print("Expected Results:\n", y_xor)
print("\nFinal Results:")
print(model.predict(X_xor))

W1: [[ 0.00122399 -0.01431109  0.0076728  -0.0071954 ]
 [-0.00915834  0.00210139 -0.00287877  0.01391966]],
b1: [[ 7.50033080e-05 -5.93017255e-05  1.22475395e-10 -1.12504439e-08]], 
W2: [[ 0.00601466]
 [-0.0047168 ]
 [ 0.00043869]
 [-0.00907232]], 
b2: [[1.16531332e-06]]
Epoch 0, Loss: 0.250004

Expected Results:
 [0 1 1 0]

Final Results:
[[0]
 [0]
 [1]
 [0]]


#### Increasing Iterations and Decreasing Learning Rate
Previous iterations and learning rate: 10000, 0.1

New iterations and learning rate: 20000, 0.05

In [27]:
X_xor = np.array([[0,0], [0,1], [1,0], [1,1]])
y_xor = np.array([0, 1, 1, 0])

model2 = MLP(input_size=2, hidden_size=4, lr=0.05, epochs = 20000)
model2.fit(X_xor, y_xor)

print("Expected Results:\n", y_xor)
print("\nFinal Results:")
print(model2.predict(X_xor))

W1: [[ 0.01804935  0.01032108 -0.01767287  0.01650933]
 [-0.00637075 -0.00881396  0.00967499  0.0027973 ]],
b1: [[ 4.31589618e-10  2.21762134e-11 -2.68231744e-05  6.36496185e-05]], 
W2: [[-0.01162108]
 [-0.00054408]
 [-0.00423104]
 [ 0.01018393]], 
b2: [[4.08191061e-09]]
Epoch 0, Loss: 0.250008

W1: [[ 0.21524256  2.32732135 -2.32530637  0.02506831]
 [ 0.18893836 -2.32739066  2.32532097  0.0128244 ]],
b1: [[ 4.42844010e-01 -1.03586984e-04 -1.19855052e-05  2.68461949e-02]], 
W2: [[-0.52716751]
 [ 3.28701402]
 [ 3.28440099]
 [-0.03656559]], 
b2: [[-3.23517291]]
Epoch 10000, Loss: 0.000520

Expected Results:
 [0 1 1 0]

Final Results:
[[0]
 [1]
 [1]
 [0]]


#### Testing the model with more inputs

In [28]:
X_test = np.array([[1,1], [1,1], [0,0], [0,1], [1,0], [1,0]])
y_test = np.array([0, 0, 0, 1, 1, 1])

print("Expected Results:", y_test)
print("Final Results:\n", model2.predict(X_test))

Expected Results: [0 0 0 1 1 1]
Final Results:
 [[0]
 [0]
 [0]
 [1]
 [1]
 [1]]
